### ISSUE TITLE
Provide meaningful exception messages

### ISSUE THREAD

**Issue by eximius313** [arturmkrtchyan/iban4j#47]
This code:
```
Iban build = new Iban.Builder()
        .countryCode(CountryCode.PL)
        .bankCode("22876")
        .accountNumber("63810519014")
        .build();
    System.out.println(build);
```
throws following exception:
```
Exception in thread "main" org.iban4j.IbanFormatException: [76nu] must contain only digits.
	at org.iban4j.IbanUtil.validateBbanEntryCharacterType(IbanUtil.java:409)
	at org.iban4j.IbanUtil.validateBbanEntries(IbanUtil.java:379)
	at org.iban4j.IbanUtil.validate(IbanUtil.java:80)
	at org.iban4j.Iban$Builder.build(Iban.java:365)
	at org.iban4j.Iban$Builder.build(Iban.java:337)
```

And what is even more weird, this code:
```
    Iban randomIban = Iban.random(CountryCode.PL);
    Iban build = new Iban.Builder()
        .countryCode(CountryCode.PL)
        .bankCode(randomIban.getBankCode())
        .accountNumber(randomIban.getAccountNumber())
        .build();
```
throws following exception:
```
Exception in thread "main" org.iban4j.IbanFormatException: [270nullnull2789991694524099] length is 27, expected BBAN length is: 24
	at org.iban4j.IbanUtil.validateBbanLength(IbanUtil.java:362)
	at org.iban4j.IbanUtil.validate(IbanUtil.java:79)
	at org.iban4j.Iban$Builder.build(Iban.java:365)
	at org.iban4j.Iban$Builder.build(Iban.java:337)
```

what's wrong?

**Comment by arturmkrtchyan** [comment]
Polish IBAN's have the following structure:

```
.countryCode(CountryCode.PL)
                        .bankCode("109")
                        .branchCode("0101")
                        .accountNumber("0000071219812874")
.nationalCheckDigit("4")

**Comment by eximius313** [comment]
Could I ask then for more meaningful error messages in both cases and treat this issue as Improvement Request?

**Comment by arturmkrtchyan** [comment]
Absolutely! 
Lately I have not been actively adding feature requests, but going forward I'm planning to dedicate some time to it.

**Comment by eximius313** [comment]
Thank you so much!
I spend a lot of time debugging why `[76nu] must contain only digits` despite I provided only digits :)

**Comment by hajk1** [comment]
"Provide meaningful exception messages" — reproduced the exact code from the issue; it now throws nationalCheckDigit is required; it cannot be null instead of the garbled 2018-era messages.
